frase = input("Ingresa una frase: ")
vocal = input("Ingresa una vocal: ")
frase_a_modificar = frase.replace(vocal, vocal.upper())
print("La frase con la vocal en mayúscula es:", frase_a_modificar)
input()